- p1,p2,p3,p4 데이터
- happy, disgusted, calm, sad, fear, confused, surprised, angry 수치 데이터가 있고
- emtion(target 변수)에는 p(positive),z(normal),n(negative) 정보가 있음

In [4]:
# 내가 열 순서가 다 달라서 지금 따로따로 만들었는데, 
# 데이터를 미리 열 순서를 맞춰야할지 파이썬으로 맞출지 고민

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.formula.api import ols
from statsmodels.api import qqplot, add_constant
import statsmodels.formula.api as smf
from statsmodels.tools.eval_measures import rmse
# % matplotlib inline

In [14]:
from sklearn.tree import export_graphviz
import graphviz

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [16]:
 # 일단 데이터 합치는 거 난제 하고,, 하나 가지고 먼저 해보자

In [46]:
df_raw = pd.read_csv('C:\\Users\\SEOJIN\\Desktop\\jongp1_2021\\train_machinelearning\\train data\\text\\p1_entire.csv', engine='python')
df_raw.head()

   HAPPY  DISGUSTED  CALM   SAD  FEAR  CONFUSED  SURPRISED  ANGRY emotion
0     98          0      0    0     0         0          0      0       p
1     99          0      0    0     0         0          0      0       p
2     99          0      0    0     0         0          0      0       p
3     99          0      0    0     0         0          0      0       p
4     99          0      0    0     0         0          0      0       p

In [ ]:
df_1 = pd.read_csv('C:\\Users\\SEOJIN\\Desktop\\jongp1_2021\\train_machinelearning\\train data\\text\\p1_entire.csv', engine='python')
df_2 = pd.read_csv('C:\\Users\\SEOJIN\\Desktop\\jongp1_2021\\train_machinelearning\\train data\\text\\p2_entire.csv', engine='python')
df_3 = pd.read_csv('C:\\Users\\SEOJIN\\Desktop\\jongp1_2021\\train_machinelearning\\train data\\text\\p3_entire.csv', engine='python')
df_4 = pd.read_csv('C:\\Users\\SEOJIN\\Desktop\\jongp1_2021\\train_machinelearning\\train data\\text\\p4_entire.csv', engine='python')

In [47]:
plt.rc('font',family='NanumGothic')

In [48]:
# 데이터가 적어서 교차 검증을 해야할 것 같은데,, oob_score, bootstrap이 관련이 있다?

In [49]:
# p : 2 z : 1 n : 0
for i in range(len(df_raw['emotion'])):
    if df_raw['emotion'][i] == 'p':
        df_raw['emotion'][i] = 2
    elif df_raw['emotion'][i] == 'z':
        df_raw['emotion'][i] = 1
    else:
        df_raw['emotion'][i] = 0
# df_raw['emotion'] = np.where(df_raw['emotion']=='p',2)
# df_raw['emotion'] = np.where(df_raw['emotion']=='z',1)
# df_raw['emotion'] = np.where(df_raw['emotion']=='n',0)
df_raw.head(50)

<ipython-input-49-b2a43bc2c133>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_raw['emotion'][i] = 2
<ipython-input-49-b2a43bc2c133>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_raw['emotion'][i] = 1
<ipython-input-49-b2a43bc2c133>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_raw['emotion'][i] = 0

    HAPPY  DISGUSTED  CALM   SAD  FEAR  CONFUSED  SURPRISED  ANGRY emotion
0      98          0      0    0     0         0          0      0       2
1      99          0      0    0     0         0          0      0       2
2      99          0      0    0     0         0          0      0       2
3      99          0      0    0     0         0          0      0       2
4      99          0      0    0     0         0          0      0       2
5      96          2      0    0     0         0          0      0       2
6      99          0      0    0     0         0          0      0       2
7      98          0      0    0     0         0          0      0       2
8      97          0      0    0     0         0          0      0       2
9      98          0      0    0     0         0          0      0       2
10     99          0      0    0     0         0          0      0       2
11     99          0      0    0     0         0          0      0       2
12     92          6      0    0     0         0          0      0       2
13     99          0      0    0     0         0          0      0       2
14    100          0      0    0     0         0          0      0       2
15     99          0      0    0     0         0          0      0       2
16     99          0      0    0     0         0          0      0       2
17    100          0      0    0     0         0          0      0       2
18    100          0      0    0     0         0          0      0       2
19    100          0      0    0     0         0          0      0       2
20    100          0      0    0     0         0          0      0       2
21    100          0      0    0     0         0          0      0       2
22    100          0      0    0     0         0          0      0       2
23      0         21     56    6     0         0          0      6       1
24      0         28     41    0     0         0          0      9       1
25      0          8     31    8     0         0          0     45       1
26      3         78     14    0     0         0          0      0       1
27     22         36     28    0     0         0          0      0       1
28     44         28     19    0     0         0          0      0       1
29      1         97      0    0     0         0          0      0       1
30      5         90      2    0     0         0          0      0       1
31      0         93      1    0     0         0          0      1       1
32      0         45     26    0     0         0          0     10       1
33      0         79      7    0     0         0          0      7       1
34      0         37     13    0     0         0          0     37       1
35      0          0     45    9     0         0          0     25       1
36      0          7     11    0     0         0          0     70       1
37      0         18     10    0     0         0          0     54       1
38      0         15     14    0     0         0          0     55       1
39      0         14     13    0     0         0          0     50       1
40      0         92      0    0     0         0          0      3       0
41      0         86      0    0     0         0          0      5       0
42      0         61      0    0     0         0          0     12       0
43      0         52      0    0     0         0          0     16       0
44      0         69      0    0     0         0          0     10       0
45      0         72      0    0     0         0          0      9       0
46      0         51      0    0     0         0          0     16       0
47      0         54      0    0     0         0          0     13       0
48      0         61      0    0     0         0          0     21       0
49      0         57      0    0     0         0          0     20       0

In [50]:
# 일단 , 잘 모르겠지만 ㄱㄱ해보자

In [51]:
df_raw_y = df_raw['emotion']
df_raw_x = df_raw.drop('emotion', axis=1, inplace=False)

In [52]:
df_train_x, df_test_x, df_train_y, df_test_y = train_test_split(df_raw_x, df_raw_y, test_size=0.3, random_state=1234)

print('Train Data X size: {}'.format(df_train_x.shape))
print('Train Data Y size: {}'.format(df_train_y.shape))
print('Test Data X size: {}'.format(df_test_x.shape))
print('Test Data Y size: {}'.format(df_test_y.shape))

Train Data X size: (42, 8)
Train Data Y size: (42,)
Test Data X size: (19, 8)
Test Data Y size: (19,)

In [54]:
# 아마도 default로 했을 때?
rf_uncustomized = RandomForestRegressor(random_state=1234)
rf_uncustomized.fit(df_train_x, df_train_y)

print('Score on training set:{:.3f}'.format(rf_uncustomized.score(df_train_x, df_train_y)))
print('Score on test set:{:.3f}'.format(rf_uncustomized.score(df_test_x, df_test_y)))

Score on training set:0.994
Score on test set:0.976